Cleanup

diff --git a/libexec/cli-common-core-help b/libexec/cli-common-core-help
--- a/libexec/cli-common-core-help
+++ b/libexec/cli-common-core-help
@@ -2,7 +2,7 @@
 #
 # Summary: Display help for a command
 #
-# Usage: rbenv help [--usage] COMMAND
+# Usage: cli-common-core help [--usage] COMMAND
 #
 # Parses and displays help contents from a command's source file.
 #
@@ -13,17 +13,12 @@
 # documentation.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$CLI_COMMON_CORE_DEBUG" ] && set -x
 
-# Provide rbenv completions
-if [ "$1" = "--complete" ]; then
-  echo --usage
-  exec rbenv-commands
-fi
 
 command_path() {
   local command="$1"
-  command -v rbenv-"$command" || command -v rbenv-sh-"$command" || true
+  command -v cli-common-core-"$command" || command -v cli-common-core-sh-"$command" || true
 }
 
 extract_initial_comment_block() {
@@ -45,7 +40,7 @@ collect_documentation() {
   local awk
   awk="$(type -p gawk awk 2>/dev/null | head -1)"
   if [ -z "$awk" ]; then
-    echo "rbenv: cannot find awk" >&2
+    echo "cli-common-core: cannot find awk" >&2
     return 1
   fi
 
@@ -127,7 +122,7 @@ print_help() {
     if [ -n "$usage" ]; then
       echo "$usage"
     else
-      echo "Usage: rbenv ${command}"
+      echo "Usage: cli-common-core ${command}"
     fi
     if [ -n "$help" ]; then
       echo
@@ -153,15 +148,15 @@ if [ "$1" = "--usage" ]; then
   shift
 fi
 
-if [ -z "$1" ] || [ "$1" == "rbenv" ]; then
-  echo "Usage: rbenv <command> [<args>]"
+if [ -z "$1" ] || [ "$1" == "cli-common-core" ]; then
+  echo "Usage: cli-common-core <command> [<args>]"
   [ -z "$usage" ] || exit
   echo
-  echo "Some useful rbenv commands are:"
-  print_summaries commands local global shell install uninstall rehash version versions which whence
+  echo "Some useful cli-common-core commands are:"
+  print_summaries commands local global shell install uninstall rehash version versions which whence example
   echo
-  echo "See \`rbenv help <command>' for information on a specific command."
-  echo "For full documentation, see: https://github.com/rbenv/rbenv#readme"
+  echo "See \`cli-common-core help <command>' for information on a specific command."
+  echo "For full documentation, see: https://github.com/la-ruby/cli-common-core#readme"
 else
   command="$1"
   if [ -n "$(command_path "$command")" ]; then
@@ -171,7 +166,7 @@ else
       print_help "$command"
     fi
   else
-    echo "rbenv: no such command \`$command'" >&2
+    echo "cli-common-core: no such command \`$command'" >&2
     exit 1
   fi
 fi
